title: Jiangeng Dong
email: dongjiangeng@gmail.com
author: Jiangeng Dong
baseurl: ""
url: ""
github_username:  jiangengdong

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

header_pages:
  - pages/index.md
  - pages/publication.md
  - pages/research.md
